version: '3.8'

services:
  django:
    build: .
    volumes:
      - .:/opt/services/django/src
    env_file:
      - .env
    networks:
      - nginx_network
  
  nginx:
    image: nginx:1.18.0
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - django
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge